### ISSUE TITLE
I need help with my new language support.

### ISSUE THREAD

**Issue by Cardroid** [DYVAUX/nnsvs-english-support#1]
Hello,
I've been to many places to implement new language support for NNSVS. And I found this repo.
https://github.com/r9y9/nnsvs/issues/63

I think NNSVS can support a new language with only a table and hed file for the new language.

To me, you seem to be an expert.
Do you have detailed instructions to support the new language?

Thank you in advance.

**Comment by ghost** [comment]
What is the language? It may already be supported by someone else.

**Comment by Cardroid** [comment]
@causticism 

It's Korean.
I've looked at several projects, but there's no place to apply.
So if I can see the documents with the rules on them, I want to make them myself.

Thank you for your answer.

**Comment by Auxthority** [comment]
There is already someone working on Korean support for NNSVS, you can ask further questions about it on the nnsvs community server.

There is a community-provided tutorial here: https://docs.google.com/document/d/1uMsepxbdUW65PfIWL1pt2OM6ZKa5ybTTJOpZ733Ht6s/edit?usp=drivesdk
And you may join the server here: https://discord.gg/HbruQZ4

I'll now be closing this issue as it does not pertrain to English support

**Comment by ghost** [comment]
There is already someone working on Korean support for NNSVS, you can ask further questions about it on the nnsvs community server.

There is a community-provided tutorial here: https://docs.google.com/document/d/1uMsepxbdUW65PfIWL1pt2OM6ZKa5ybTTJOpZ733Ht6s/edit?usp=drivesdk
And you may join the server here: https://discord.gg/HbruQZ4

**Comment by Cardroid** [comment]
Thank you so much! 👍
